### ISSUE TITLE
Cartelera (tiempo pelis)

### ISSUE THREAD

**Issue by DACR-DC** [Frls03/Software_de_taquilla_C#28]
El tiempo de las películas tiene como limite 100 y la de barbie dura 154 minutos quizás ajustarlo para un limite de 3 horas(180 mins) o más, también seria buena idea especificar que la duración es en minutos como duración(mins) o algo así. Gracias :D

**Comment by Olivers11** [comment]
Ya se arreglo este error, la linea de tiempo abarca el total de la duracion sobre el maximo que es de 500 min
