### ISSUE TITLE
rol

### ISSUE THREAD

**Issue by DACR-DC** [Frls03/Software_de_taquilla_C#29]
En la parte de selección de rol considero que se debería prohibir el escribir ya que se puede modificar en donde se despliegan los roles a escoger. Que no se permita escribir nada. Gracias :D
![error](https://github.com/Frls03/Software_de_taquilla_C/assets/94415372/f4a3cb80-313f-49fb-9c7b-078bd79d4d51)

**Comment by Olstertecn11** [comment]
Me encanta la observacion gracias David, lo arreglare!

**Comment by Olivers11** [comment]
El error ya fue corregido, muchas gracias por la observacion :D
