### ISSUE TITLE
Error en Usermanagment

### ISSUE THREAD

**Issue by coradoa** [Frls03/Software_de_taquilla_C#37]
Al momento de darle actualizar donde no hay nada seleccionado y lo colocas ahí, tira un error en el cual es porque esta en vacía y seria bueno que tirara algo como seleccione persona a actualizar o algo así.

**Comment by Olstertecn11** [comment]
This problem is fixed in: [ This Commit](https://github.com/Frls03/Software_de_taquilla_C/pull/39/commits/3d1c6d66e90f2737e3b53cfcc0677a511d5facb3)
