### ISSUE TITLE
usuarios actualizar espacio vacío

### ISSUE THREAD

**Issue by DACR-DC** [Frls03/Software_de_taquilla_C#41]
Si por accidente se actualiza un espacio vacío quizás se debería mostrar un mensaje que indique que por favor indique un usuario ya registrado para ser actualizado en lugar del siguiente mensaje. Gracias y buenas tardes.   

![error1](https://github.com/Frls03/Software_de_taquilla_C/assets/94415372/cda03277-6dab-4710-96c8-e2cc1733b4ab)

**Comment by Olivers11** [comment]
Arreglado en el ultimo commit
