### ISSUE TITLE
Cine no pertenece a ciudad

### ISSUE THREAD

**Issue by DACR-DC** [Frls03/Software_de_taquilla_C#59]
En la selección de cine en Quetzaltenango no debería de existir miraflores.

![error2](https://github.com/Frls03/Software_de_taquilla_C/assets/94415372/657840cd-bd4f-440e-b615-2fc2ad5c879f)

**Comment by Olivers11** [comment]
![image](https://github.com/Frls03/Software_de_taquilla_C/assets/55993708/0aa96910-048b-4533-a3cc-5ccb40da27b6)
Así o mas crack?
