### ISSUE TITLE
Problema subir imagen peliculas

### ISSUE THREAD

**Issue by DACR-DC** [Frls03/Software_de_taquilla_C#60]
En las pruebas si se sube una imagen muy grande causa un error en el programa.  

![error3](https://github.com/Frls03/Software_de_taquilla_C/assets/94415372/19b0fa87-ff35-4ce8-87c4-be44e5d7b7b9)

**Comment by Olivers11** [comment]
![image](https://github.com/Frls03/Software_de_taquilla_C/assets/55993708/2c110c52-71ed-4e0a-8c79-9a169443cedc)
Ya bitch
